### ISSUE TITLE
Selector to get visibility state

### ISSUE THREAD

**Issue by klimashkin** [retyui/redux-saga-document-visibility#2]
Would be also great to have some selector to decide if we need to start doing something in saga on its start if document is visible.

**Comment by retyui** [comment]
@klimashkin 
I made this saga as an event generator without reference to the story.
Since the only value that is available is the `document.visibilityState`, you do not need a selector, you can access the values directly
```js
const isPageVisible = () => document.visibilityState === 'visible';

function* exmaple(){
     if(isPageVisible()){
         // do something
         yield call(someFn, arg);
     }
}
```

**Comment by klimashkin** [comment]
I was thinking about crossbrowser usage, but figured it's ok to use `Visibility.hidden()` from [visibilityjs](https://github.com/ai/visibilityjs).
Thank you!

**Comment by retyui** [comment]
At the moment this property is well supported without prefixes

![image](https://user-images.githubusercontent.com/4661784/41143249-494af94e-6b01-11e8-8dca-472badd50834.png)
