### ISSUE TITLE
How to get rid of babel regenerator

### ISSUE THREAD

**Issue by klimashkin** [retyui/redux-saga-document-visibility#3]
Hi!
I'm building application separately for old/new browsers, and for the new ones I use this babel-transform config:
```javascript
['@babel/plugin-transform-runtime', {
  polyfill: false, regenerator: false, helpers: true,
  useESModules: true, useBuiltIns: true,
  moduleName: '@babel/runtime',
}],
```
To turn off regenerator.

But if I require `redux-saga-document-visibility` it forcibly requires `@babel/runtime/regenerator` which makes shipped size of `redux-saga-document-visibility` several times bigger than its original src size.

Can we ship here also 2015+ version? I did it in one of my modules https://github.com/klimashkin/react-forwardref-utils (for reference)

**Comment by retyui** [comment]
@klimashkin 
Here [example](https://github.com/retyui/redux-saga-document-visibility/blob/master/examples/webpack-build-without-babel-runtime/README.md)
